### ISSUE TITLE
VS2017 企业版 安装AProtobuf ,打开proto文件报错.

### ISSUE THREAD

**Issue by JasonDevStudio** [alittlesail/AProtobuf-VSIX#1]
VS2017 企业版 安装AProtobuf ,打开proto文件报错. 很好复现

**Comment by alittlesail** [comment]
我现在手头没有安装VS2017，报的错误内容是否可以提出来下

**Comment by JasonDevStudio** [comment]
<description>System.NullReferenceException: &#x672A;&#x5C06;&#x5BF9;&#x8C61;&#x5F15;&#x7528;&#x8BBE;&#x7F6E;&#x5230;&#x5BF9;&#x8C61;&#x7684;&#x5B9E;&#x4F8B;&#x3002;&#x000D;&#x000A;   &#x5728; ALittle.BaseOptionModel`1.&lt;LoadAsync&gt;d__9.MoveNext()&#x000D;&#x000A;--- &#x5F15;&#x53D1;&#x5F02;&#x5E38;&#x7684;&#x4E0A;&#x4E00;&#x4F4D;&#x7F6E;&#x4E2D;&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x7684;&#x672B;&#x5C3E; ---&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x5728; ALittle.BaseOptionModel`1.&lt;CreateAsync&gt;d__14.MoveNext()&#x000D;&#x000A;--- &#x5F15;&#x53D1;&#x5F02;&#x5E38;&#x7684;&#x4E0A;&#x4E00;&#x4F4D;&#x7F6E;&#x4E2D;&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x7684;&#x672B;&#x5C3E; ---&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.AsyncLazy`1.&lt;&gt;c__DisplayClass13_1.&lt;&lt;GetValueAsync&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- &#x5F15;&#x53D1;&#x5F02;&#x5E38;&#x7684;&#x4E0A;&#x4E00;&#x4F4D;&#x7F6E;&#x4E2D;&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x7684;&#x672B;&#x5C3E; ---&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   &#x5728; System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)&#x000D;&#x000A;   &#x5728; ALittle.BaseOptionModel`1.get_Instance()&#x000D;&#x000A;   &#x5728; ALittle.AProtobufFactoryClass.MainThreadInit()&#x000D;&#x000A;   &#x5728; ALittle.ABnfFactory.Init(SVsServiceProvider service_provider, IVsEditorAdaptersFactoryService adapters_factory)&#x000D;&#x000A;   &#x5728; ALittle.ALanguageVsTextViewCreationListener.VsTextViewCreated(IVsTextView text_view)&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.&lt;&gt;c__DisplayClass423_0.&lt;SendVsTextViewCreated&gt;b__0()&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)&#x000D;&#x000A;--- &#x5F15;&#x53D1;&#x5F02;&#x5E38;&#x7684;&#x4E0A;&#x4E00;&#x4F4D;&#x7F6E;&#x4E2D;&#x5806;&#x6808;&#x8DDF;&#x8E2A;&#x7684;&#x672B;&#x5C3E; ---&#x000D;&#x000A;   &#x5728; Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>

**Comment by JasonDevStudio** [comment]
双击proto文件打开报错之后,语法高亮,智能提示等全部是失效的呢. 麻烦你帮忙看看 ,谢谢.

**Comment by alittlesail** [comment]
可以告诉我你的邮箱吗，我修正了一个版本，想单独发给你试一下
